export const FETCH_WRITINGMODELS_PENDING = 'FETCH_WRITINGMODELS_PENDING';
export const FETCH_WRITINGMODELS_SUCCESS = 'FETCH_WRITINGMODELS_SUCCESS';
export const FETCH_WRITINGMODELS_FAIL = 'FETCH_WRITINGMODELS_FAIL';
export const FETCH_SUBJECTAREAS_PENDING = 'FETCH_SUBJECTAREAS_PENDING';
export const FETCH_SUBJECTAREAS_SUCCESS = 'FETCH_SUBJECTAREAS_SUCCESS';
export const FETCH_SUBJECTAREAS_FAIL = 'FETCH_SUBJECTAREAS_FAIL';
