export const FETCH_WRITINGMODELS_PENDING = 'FETCH_WRITINGMODELS_PENDING';
export const FETCH_WRITINGMODELS_SUCCESS = 'FETCH_WRITINGMODELS_SUCCESS';
export const FETCH_WRITINGMODELS_FAIL = 'FETCH_WRITINGMODELS_FAIL';

export const FETCH_SUBJECTAREAS_PENDING = 'FETCH_SUBJECTAREAS_PENDING';
export const FETCH_SUBJECTAREAS_SUCCESS = 'FETCH_SUBJECTAREAS_SUCCESS';
export const FETCH_SUBJECTAREAS_FAIL = 'FETCH_SUBJECTAREAS_FAIL';

export const FETCH_SECTIONS_PENDING = 'FETCH_SECTIONS_PENDING';
export const FETCH_SECTIONS_SUCCESS = 'FETCH_SECTIONS_SUCCESS';
export const FETCH_SECTIONS_FAIL = 'FETCH_SECTIONS_FAIL';

export const FETCH_MOVES_PENDING = 'FETCH_MOVES_PENDING';
export const FETCH_MOVES_SUCCESS = 'FETCH_MOVES_SUCCESS';
export const FETCH_MOVES_FAIL = 'FETCH_MOVES_FAIL';

export const FETCH_STEPS_PENDING = 'FETCH_STEPS_PENDING';
export const FETCH_STEPS_SUCCESS = 'FETCH_STEPS_SUCCESS';
export const FETCH_STEPS_FAIL = 'FETCH_STEPS_FAIL';

export const FETCH_MARKERS_PENDING = 'FETCH_MARKERS_PENDING';
export const FETCH_MARKERS_SUCCESS = 'FETCH_MARKERS_SUCCESS';
export const FETCH_MARKERS_FAIL = 'FETCH_MARKERS_FAIL';

export const FETCH_MDCODES_PENDING = 'FETCH_MDCODES_PENDING';
export const FETCH_MDCODES_SUCESS = 'FETCH_MDCODES_SUCESS';
export const FETCH_MDCODES_FAIL = 'FETCH_MDCODES_FAIL';

export const FETCH_MDSUBCODES_PENDING = 'FETCH_MDSUBCODES_PENDING';
export const FETCH_MDSUBCODES_SUCESS = 'FETCH_MDSUBCODES_SUCESS';
export const FETCH_MDSUBCODES_FAIL = 'FETCH_MDSUBCODES_FAIL';

export const FETCH_MDMARKERS_PENDING = 'FETCH_MDMARKERS_PENDING';
export const FETCH_MDMARKERS_SUCESS = 'FETCH_MDMARKERS_SUCESS';
export const FETCH_MDMARKERS_FAIL = 'FETCH_MDMARKERS_FAIL';

export const FETCH_SCENTENCE_BY_MARKERID_PENDING = 'FETCH_SCENTENCE_BY_MARKERID_PENDING';
export const FETCH_SCENTENCE_BY_MARKERID_SUCCESS = 'FETCH_SCENTENCE_BY_MARKERID_SUCCESS';
export const FETCH_SCENTENCE_BY_MARKERID_FAIL = 'FETCH_SCENTENCE_BY_MARKERID_FAIL';

export const INPUT_DOCUMENT_TITLE = 'INPUT_TITLE';
export const SET_DOCUMENT_BODY_BY_SECTIONID = 'SET_DOCUMENT_BODY_BY_SECTIONID';
export const SET_DOCUMENT_BODY = 'SET_DOCUMENT_BODY';

export const SET_WRITINGMODEL_ID = 'SET_WRITINGMODEL_ID';
export const SET_SUBJECTAREA_ID = 'SET_SUBJECTAREA_ID';
export const SET_SECTION_ID = 'SET_SECTION_ID';

export const SET_CURRENT_MOVE_ID = 'SET_CURRENT_MOVE_ID';
export const SET_CURRENT_STEP_ID = 'SET_CURRENT_STEP_ID';
export const SET_CURRENT_MARKER_ID = 'SET_CURRENT_MARKER_ID';

export const SET_CURRENT_MDCODE_ID = 'SET_CURRENT_MDCODE_ID';
export const SET_CURRENT_MDSUBCODE_ID = 'SET_CURRENT_MDSUBCODE_ID';
export const SET_CURRENT_MDMARKER_ID = 'SET_CURRENT_MDMARKER_ID';

export const SET_POPUP_ACTIVE = 'SET_POPUP_ACTIVE';

export const SET_ANALYSIS = 'SET_ANALYSIS';
export const SET_ANALYSIS_SENTENCE_ID = 'SET_ANALYSIS_SENTENCE_ID';

export const SET_ANALYSIS_FLAG = 'SET_ANALYSIS_FLAG';
export const SET_GUIDE_FLAG = 'SET_GUIDE_FLAG';

export const SET_RIGHTPANEL_TAB = 'SET_RIGHTPANEL_TAB';
