export const FETCH_WRITINGMODELS_PENDING = 'FETCH_WRITINGMODELS_PENDING';
export const FETCH_WRITINGMODELS_SUCCESS = 'FETCH_WRITINGMODELS_SUCCESS';
export const FETCH_WRITINGMODELS_FAIL = 'FETCH_WRITINGMODELS_FAIL';

export const FETCH_SUBJECTAREAS_PENDING = 'FETCH_SUBJECTAREAS_PENDING';
export const FETCH_SUBJECTAREAS_SUCCESS = 'FETCH_SUBJECTAREAS_SUCCESS';
export const FETCH_SUBJECTAREAS_FAIL = 'FETCH_SUBJECTAREAS_FAIL';

export const FETCH_SECTIONS_PENDING = 'FETCH_SECTIONS_PENDING';
export const FETCH_SECTIONS_SUCCESS = 'FETCH_SECTIONS_SUCCESS';
export const FETCH_SECTIONS_FAIL = 'FETCH_SECTIONS_FAIL';

export const INPUT_DOCUMENT_TITLE = 'INPUT_TITLE';
export const INPUT_DOCUMENT_BODY = 'INPUT_DOCUMENT_BODY';
export const SET_DOCUMENT_SECTION_ID = 'SET_DOCUMENT_SECTION_ID'; // 1-Introduction  2-Literature Review

export const SET_FUNCTIONPANEL_ACTIVE = 'SET_FUNCTIONPANEL_ACTIVE'; // show or hide function panel

export const SET_WRITINGMODEL_ID = 'SET_WRITINGMODEL_ID';
export const SET_SUBJECTAREA_ID = 'SET_SUBJECTAREA_ID';
